// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using MedicalSystem.Models;

namespace MedicalSystem.Data
{
    public partial class MedicalSystemContext
    {

        [DbFunction("getDoctorRating", "dbo")]
        public static int? getDoctorRating(int? doc)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
