// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Table("Doctor")]
    public partial class Doctor
    {
        public Doctor()
        {
            Records = new HashSet<Record>();
            Visits = new HashSet<Visit>();
            Works_ins = new HashSet<Works_in>();
        }

        [Key]
        public int ID { get; set; }

        [StringLength(20, MinimumLength = 2)]
        [Required(ErrorMessage = "first name is required")]
        [Unicode(false)]
        public string Fname { get; set; }

        [StringLength(20, MinimumLength = 2)]
        [Required(ErrorMessage = "last name is required")]
        [Unicode(false)]
        public string Lname { get; set; }

        [Required(ErrorMessage = "birthDate is required")]
        public DateTime birthDate { get; set; }

        [EmailAddress]
        [Required(ErrorMessage = "Email is required")]
        [Unicode(false)]
        public string email { get; set; }

        [Required(ErrorMessage = "City is required")]
        [Unicode(false)]
        public string city { get; set; }
        public string area { get; set; }
        public string street { get; set; }
        public int? buildingNumber { get; set; }


        [Required(ErrorMessage = "Phone is required")]
        public int? phone { get; set; }

        //[Required(ErrorMessage = "Username is required")]
        //[StringLength(25, MinimumLength = 2)]
        //[Unicode(false)]
        //public string username { get; set; }

        [Required(ErrorMessage = "password is required")]
        //[RegularExpression("^(?=.*[A-Za-z])(?=.*/d)[A-Za-z/d]{8,}$")]
        [Unicode(false)]
        public string password { get; set; }
        [Unicode(false)]
        public string category { get; set; }

        public string profilePic { get; set; }

        public char gender { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public int? age { get; set; }

        [InverseProperty("DIDNavigation")]
        public virtual ICollection<Record> Records { get; set; }
        [InverseProperty("DIDNavigation")]
        public virtual ICollection<Visit> Visits { get; set; }
        [InverseProperty("DIDNavigation")]
        public virtual ICollection<Works_in> Works_ins { get; set; }
    }
}