// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Index("email", Name = "IX_Others", IsUnique = true)]
    public partial class Other
    {
        public Other()
        {
            Records = new HashSet<Record>();
        }

        [StringLength(200)]
        public string street { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Fname { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Lname { get; set; }
        public int? age { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string email { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string phone { get; set; }
        [Required]
        [Unicode(false)]
        public string password { get; set; }
        [StringLength(50)]
        public string area { get; set; }
        public DateTime birthDate { get; set; }
        public int? buildingNumber { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string city { get; set; }
        public string profilePic { get; set; }
        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string job { get; set; }

        [InverseProperty("OIDNavigation")]
        public virtual ICollection<Record> Records { get; set; }
    }
}