// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Table("Visit")]
    [Index("DID", Name = "IX_Visit_DID")]
    public partial class Visit
    {
        [Key]
        public int PID { get; set; }
        [Key]
        public int DID { get; set; }
        [Key]
        public DateTime appointment_time { get; set; }

        public int? AppointmentStatus { get; set; }

        [ForeignKey("DID")]
        [InverseProperty("Visits")]
        public virtual Doctor DIDNavigation { get; set; }
        [ForeignKey("PID")]
        [InverseProperty("Visits")]
        public virtual Patient PIDNavigation { get; set; }
    }
}