// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Table("Works_in")]
    public partial class Works_in
    {
        [Key]
        public int DID { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int W_ID { get; set; }

        [StringLength(100)]
        [Unicode(false)]
        public string start_time { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string end_time { get; set; }

        [Required]
        public int maxpatientNo { get; set; }

        [ForeignKey("DID")]
        [InverseProperty("Works_ins")]
        public virtual Doctor DIDNavigation { get; set; }
    }
}