// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Table("Clinic")]
    public partial class Clinic
    {
        public Clinic()
        {
            Visits = new HashSet<Visit>();
            Works_ins = new HashSet<Works_in>();
        }

        [Key]
        public int ID { get; set; }

        [StringLength(30, MinimumLength = 2)]
        [Required(ErrorMessage = "Name is required")]
        [Unicode(false)]
        public string name { get; set; }

        [StringLength(40, MinimumLength = 10)]
        [Required(ErrorMessage = "Address is required")]
        [Unicode(false)]
        public string address { get; set; }

        [Phone]
        [Required(ErrorMessage = "Phone is required")]
        public int? phone { get; set; }

        [InverseProperty("CIDNavigation")]
        public virtual ICollection<Visit> Visits { get; set; }
        [InverseProperty("CIDNavigation")]
        public virtual ICollection<Works_in> Works_ins { get; set; }
    }
}