// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Table("Patient")]
    public partial class Patient
    {
        public Patient()
        {
            Records = new HashSet<Record>();
            Visits = new HashSet<Visit>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Fname { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Lname { get; set; }
        public int? age { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string email { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string address { get; set; }
        public int? phone { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string username { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string password { get; set; }

        [InverseProperty("PIDNavigation")]
        public virtual ICollection<Record> Records { get; set; }
        [InverseProperty("PIDNavigation")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}