// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Table("Patient")]
    public partial class Patient
    {
        public Patient()
        {
            Records = new HashSet<Record>();
            Visits = new HashSet<Visit>();
        }

        [Key]
        public int ID { get; set; }

        [StringLength(20 , MinimumLength = 2)]
        [Required(ErrorMessage = "first name is required")]
        [Unicode(false)]
        public string Fname { get; set; }

        [StringLength(20, MinimumLength = 2)]
        [Required(ErrorMessage = "last name is required")]
        [Unicode(false)]
        public string Lname { get; set; }

        [Required(ErrorMessage ="Age is required")]
        [Range(0,110,ErrorMessage ="Out of range")]
        public int? age { get; set; }

        [EmailAddress]
        [Required(ErrorMessage = "Email is required")]
        [Unicode(false)]
        public string email { get; set; }

        [StringLength(40, MinimumLength = 10)]
        [Required(ErrorMessage = "Address is required")]
        [Unicode(false)]
        public string address { get; set; }

        [Phone]
        [Required(ErrorMessage ="Phone is required")]
        public int? phone { get; set; }

        [Required(ErrorMessage = "Username is required")]
        [StringLength(25, MinimumLength = 2)]
        [Unicode(false)]
        public string username { get; set; }

        [Required(ErrorMessage = "password is required")]
        [RegularExpression("^(?=.*[A-Za-z])(?=.*/d)[A-Za-z/d]{8,}$")]
        [Unicode(false)]
        public string password { get; set; }

        [InverseProperty("PIDNavigation")]
        public virtual ICollection<Record> Records { get; set; }
        [InverseProperty("PIDNavigation")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}