// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Table("Visit")]
    public partial class Visit
    {
        [Key]
        public int PID { get; set; }
        [Key]
        public int DID { get; set; }
        [Key]
        public int CID { get; set; }
        public DateTime? appointment_time { get; set; }

        [ForeignKey("CID")]
        [InverseProperty("Visits")]
        public virtual Clinic CIDNavigation { get; set; }
        [ForeignKey("DID")]
        [InverseProperty("Visits")]
        public virtual Doctor DIDNavigation { get; set; }
        [ForeignKey("PID")]
        [InverseProperty("Visits")]
        public virtual Patient PIDNavigation { get; set; }
    }
}