// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MedicalSystem.Models
{
    [Table("Works_in")]
    public partial class Works_in
    {
        [Key]
        public int DID { get; set; }
        [Key]
        public int CID { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime? start_time { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime? end_time { get; set; }

        [ForeignKey("CID")]
        [InverseProperty("Works_ins")]
        public virtual Clinic CIDNavigation { get; set; }
        [ForeignKey("DID")]
        [InverseProperty("Works_ins")]
        public virtual Doctor DIDNavigation { get; set; }
    }
}